api_key: 'key-00189745ce652e42d6f1ee591b9f4f6a'
domain: 'gmail.com'
username: 'postmaster@sandboxa6a6272d42e5487f85b6059b25fac83e.mailgun.org'
password: '0b8160d41456ab17f399be5d744abba2'
gmail_username: 'philotester5@gmail.com'
gmail_password: 'Worringen1'
