# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9a03992f3fd20f69bdf805c3f41525ff9f0c8b6de6ae47bef489173471221f52b4a80e11ff786ed6c24e8571122e800e58c05f4c3728e12e373fc82eaed176
  postgres: 'Worringen1'

test:
  secret_key_base: 113721183a64ead6d8090a62833e7091aabc3a8c90b467b38e56bb4441c364fae2299b306f921936f4386932a3f8887d5dccc5f39c937a2cf3cc9f6156d81865
  postgres: 'Worringen1'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: 'key-00189745ce652e42d6f1ee591b9f4f6a'
  domain: 'sandboxa6a6272d42e5487f85b6059b25fac83e.mailgun.org'
  username: 'postmaster@sandboxa6a6272d42e5487f85b6059b25fac83e.mailgun.org'
  password: '0b8160d41456ab17f399be5d744abba2'
  gmail_username: 'philotester5@gmail.com'
  gmail_password: 'Worringen1'
  postgres: 'Worringen1'